name: nmaglev
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: erlang:22
          - image: erlang:23
          - image: erlang:24
    runs-on: self-hosted
    container:
      image: ${{ matrix.image }}
      options: "--entrypoint /bin/bash"

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Inspect rebar3 version
      - name: Rebar version
        run: rebar3 --version

      # PRE Checks
      - name: Checks
        run: rebar3 fmt --check

      # Compile
      - name: Compile
        run: make

      # Tests
      - name: Run tests
        run: make test
      - name: Store test logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ct-logs
          path: _build/test/logs

      # Cover reports
#      - name: Create Cover Reports
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: rebar3 do cover,coveralls send
